name: .NET Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Specify your .NET SDK version here.

      - name: Clean
        run: dotnet clean PizzaHub.UnitTests/PizzaHub.UnitTests.csproj

      - name: Restore dependencies
        run: dotnet restore PizzaHub.UnitTests/PizzaHub.UnitTests.csproj

      - name: Build
        run: dotnet build PizzaHub.UnitTests/PizzaHub.UnitTests.csproj --configuration Release

      - name: Run tests
        run: dotnet test PizzaHub.UnitTests/PizzaHub.UnitTests.csproj --verbosity normal
